version: "3"

services:
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=hello_django_dev

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    tty: true
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app/frontend:cached

  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    env_file:
      - backend/.env.dev
    depends_on:
      - frontend
      - db
    environment:
      - ROOFTOP_VERSION=dev
    volumes:
      - ./backend:/app/backend:cached
    stdin_open: true
    tty: true

volumes:
  postgres_data:
