version: "3"

services:
  frontend:
    # command: npm start
    build:
      context: frontend
      dockerfile: Dockerfile
    tty: true
    ports:
      - 3000:3000

  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    env_file:
      - backend/.env.dev
    depends_on:
      - frontend
    environment:
      - ROOFTOP_VERSION=dev
    stdin_open: true
    tty: true
